# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Amicales',
    'version': '16.0',
    'category': 'TDSI',
    'summary': 'AmicaleKS',
    'description': "",
    'website': 'https://www.odoo.com/page/mescourse',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/universite_views.xml',
        'views/faculte_views.xml',
        'views/departement_views.xml',
        'views/niveau_views.xml',
        'views/promotion_views.xml',
        'views/etudiant_views.xml',
        'views/membre_views.xml',
        'views/commission_views.xml',
        'templates/membre.xml',
        'templates/membre_template_tree.xml',
        'templates/etudiant.xml',
        'templates/etudiant_create.xml',
        'templates/universite.xml',
        'templates/faculte.xml',
        'templates/promotion.xml',
        'templates/niveau.xml',
        'templates/departement.xml',
        'templates/commission.xml',
        'templates/amicale_tree.xml',
        'templates/amicale_create.xml',
        'templates/commission_create.xml',
        'templates/departement_create.xml',
        'templates/niveau_create.xml',
        'templates/promotion_create.xml',
        'templates/faculte_create.xml',
        'templates/universite_cretae.xml',
        'views/amicale_views.xml',
        'templates/index.xml',
        'templates/amicale.xml',
        'templates/a_propos.xml',
        'templates/fairedon.xml',
        'templates/membre.xml',
        'templates/programme.xml',
        'templates/header.xml',
        'templates/footer.xml',




    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
    'license': 'LGPL-3',
    'images':['/static/src/images/'],
}
