from . import universite
from . import faculte
from . import departement
from . import niveau
from . import promotion
from . import etudiant
from . import membre
from . import commission
from . import amicale